default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: dev
  host: localhost
  port: 5432
  database: meal_planner

test:
  <<: *default
  username: dev
  host: localhost
  port: 5432
  database: meal_planner_test
